name: Auto-update EPG

# Workflow schedule: har ghanta run karega, manual trigger vi possible
on:
  schedule:
    - cron: '0 * * * *'  # har ghante run
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Download latest EPG
      - name: Download latest EPG gzip
        run: |
          curl -L -o epg.xml.gz https://raw.githubusercontent.com/mitthu786/tvepg/main/epg.xml.gz

      # Step 3: Uncompress to XML
      - name: Uncompress to XML
        run: |
          gzip -d -f epg.xml.gz

      # Step 4: Commit & push XML using PAT
      - name: Commit & push XML
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add epg.xml
          git commit -m "Auto-update EPG $(date)" || echo "No changes"
          git push https://$GH_PAT@github.com/diljankhehra-cpu/sony-sab-epg.git HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
